### ISSUE TITLE
Lizenz auswählen

### ISSUE THREAD

**Issue by fabianlupa** [inventory-manager/inventory-manager#1]

**Comment by DerKaito** [comment]
Ich würde eine auswählen die das Copyleft beschützt

**Comment by oOAbaddonOo** [comment]
Ein Überblick:
http://choosealicense.com/licenses/

**Comment by Paretos** [comment]
Wenn ich unsere Ziele bedenke würde ich zu GNU GPL v3.0 tendieren. Wie seht ihr das?

Oder sollen wir die kommerzielle Nutzung von Derivaten unterbinden?

**Comment by fabianlupa** [comment]
Die Frage ist wohl auch was unser Auftraggeber für Anforderungen stellt. Wenn er die Software selbst inhouse warten / erweitern können will, müssen wir das lizenztechnisch berücksichtigen.

**Comment by Paretos** [comment]
Das ist durchaus richtig. Aber diese Anforderung wird durch GPL v3.0 abgedeckt.
