### ISSUE TITLE
Datenbankschema erstellen

### ISSUE THREAD

**Issue by fabianlupa** [inventory-manager/inventory-manager#2]

**Comment by fabianlupa** [comment]
ERM haben wir schon, es müssen nur noch die ORM Klassen (Doctrine) erstellt werden.

**Comment by fabianlupa** [comment]
Fyi https://github.com/inventory-manager/inventory-manager/wiki/ERM

**Comment by Paretos** [comment]
Vielen Dank! Werde dann zeitnah beginnen.
