### ISSUE TITLE
Startseite implementieren

### ISSUE THREAD

**Issue by DerKaito** [inventory-manager/inventory-manager#31]
Eine Startseite müsste noch gemacht werden

**Comment by fabianlupa** [comment]
Funktionen:
- Anzeige und Absprungmöglichkeit für
  - [ ] Geräte die demnächst ablaufen
  - [ ] Neu hinzugefügte Geräte

Technischer Ansatz:
- [ ] API Endpunkte für Startseite erstellen
- [ ] Frontend anpassen und an API binden
